### ISSUE TITLE
Openai Gym Interface

### ISSUE THREAD

**Issue by bhairavmehta95** [SIRLab/VSS-Simulator#16]
Is there a Python wrapper / OpenAI gym interface that people can use with this simulator?

**Comment by johnfercher** [comment]
Currently, we don't have an interface to communicate with this project in Python. We have a version in C++ (https://github.com/VSS-SDK/VSS-Core) and a version in Rust (https://github.com/VSS-SDK/VSS-CoreRust).

The good news is that we have in our roadmap interest to build and maintain a VSS-CorePy :D, but the project has not started yet. I think that will be easy to build due the use of ZMQ + Protobuf. If you have hurry to use a Python interface you can use these protofiles (https://github.com/VSS-SDK/VSS-Core/tree/master/protos) and look at these communication interfaces (https://github.com/VSS-SDK/VSS-Core/tree/master/src/Communications) to start the development of the project. Obviously, we can help you with this project.

**Comment by johnfercher** [comment]
We created a wrapper in Python, you can see here: https://github.com/VSS-SDK/VSS-SamplePy. It uses this lib https://github.com/VSS-SDK/VSS-CorePy
